version: '3.8'

services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis://redis:6379
      POSTGRES_URL: postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
